# Site Settings...
title: 'Water Parks in Ontario'

offline: false

collections:
  waterparks:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      disclaimer: "At Water Parks in Ontario we strive to keep our listings as up to date as possible but nobody's perfect. In the event of a disagreement between a water park and this website, the water park shall take precedence."
      footer_disclaimer: "In the event of a disagreement between a water park and this website, the water park shall take precedence."
  -
    scope:
      path: ""
      type: "waterparks"
    values:
      layout: "waterpark"

# Build Settings...
permalink: pretty

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md
