title: 'Water Parks in Ontario'
markdown: kramdown
offline: false
permalink: pretty

sass:
  sass_dir: css
  style:    expanded

collections:
  waterparks:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "waterparks"
    values:
      layout: "waterpark"

exclude:
- README.md
